### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by jsoref** [comment]
btw, the ghcr thing is called `corends` instead of `coredns`, I couldn't tell whether that was intentional or accidental.

**Comment by dougbw** [comment]
thanks for this! the package name is wrong so I will get that corrected in another PR

**Comment by jsoref** [comment]
(for the curious, I'm actually considering this project, as I'm deploying omada this week and looking into replacing our previous system which had local dns entries for things... -- often I do random PRs w/o much interest in the project itself.)

**Comment by dougbw** [comment]
Good luck with the Omada deployment.

The spell checker looks like an interesting project! I will take a look in to getting it built in to the CI workflow on here at some point.

**Pull request merged**
