### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by pduchnovsky**
Add default Corefile to container

Useful if ppl dont want to use mounts for such a simple file and even then they just keep it default anyway.

### CODE REVIEW

**Comment by dougbw** [comment]
Thanks for this. I think its a good idea to include a Corefile and in hindsight I should have built the image that way to begin with so that it can be configured entirely via environment variables, however I want to ensure the changes are backwards compatible with existing configurations to prevent issues when people bump to newer images - I know some users have ran into challenges deploying this in the first place so want to avoid breaking changes where possible, and as many users will already have the container images deployed with a volume mount on `/Corefile` it would conflict.

I think my preference for now would be to copy the default Corefile to another location, then add docker a CMD to specify the Corefile location. That way existing `\Corefile` mounts won't cause conflicts - they just won't be used unless the user explicitly overrides the `Corefile` location.

**Review by dougbw — APPROVED** [review]

**Comment by pduchnovsky** [comment]
@dougbw actually, having existing Corefile in the container would hurt nothing, because when user mounts Corefile, it overwrites it basically.

However, by now using /default-Corefile by default, people mounting their own configs to /Corefile means that their configs (they might've changed) would no longer be used, thus breaking their existing setups.

**Comment by dougbw** [comment]
I wasn't aware that volume mounts could overwrite existing files in an image, I am sure I ran in to issues in the past related to this but sure enough I tested it just now and it seems to work fine so I must have been mistaken! I will move it back to `/Corefile` - thanks for this

**Comment by dougbw** [comment]
This is fixed in the latest release build images now (https://github.com/dougbw/coredns_omada/releases/tag/v1.6.1) - thanks for your help

**Pull request merged**
